### ISSUE TITLE
Wildcard domains not working

### ISSUE THREAD

**Issue by Fratotec** [socram8888/dehydrated-hook-cloudflare#2]
For Wildcard domain I use aliases, like "domain1.com *.domain1.com > domain" in my domain list.
The script creates deletes old _acme-challenge records, 
creates a new record _acme-challenge.domain1.com TXT jJcJYVM8EymgHtOZE5....
then deletes the record again and greates a 2nd one.
Then the validation fails.
What´s the correct way for a wildcard cert ? The above way works fine on Amazons Route53 DNS.

**Comment by socram8888** [comment]
I didn't even knew Letsencrypt supported wildcard domains already, thus I am not sure how the DNS-01 records should be created for them.

**Comment by socram8888** [comment]
Fixed in current master.
