### ISSUE TITLE
dig result is empty

### ISSUE THREAD

**Issue by markc** [socram8888/dehydrated-hook-cloudflare#3]
FWIW on about line 110 I had to change the `| cut` to `| awk` otherwise that line would return an empty result (for me) and fail altogether.
```
#               if dig +noall +answer @ns.cloudflare.com "$fqdn" "$type" | cut -f 6- | grep -qF "$content"; then
                if dig +noall +answer @ns.cloudflare.com "$fqdn" "$type" | awk '{print $5}' | grep -qF "$content"; then
```

**Comment by socram8888** [comment]
Fixed in 37cb7955c68585b3470b12b2a9aff173cd78767a. I was hoping `dig` would use tab-separated output on all systems and thus be able to use `cut`, but apparently I was wrong.
