### ISSUE TITLE
ERROR: Missing CF keys

### ISSUE THREAD

**Issue by abecko** [socram8888/dehydrated-hook-cloudflare#7]
Hello, is the "CF_TOKEN" stored somewhere after the first run of dehydrate with the hook? Or is it always necessary to "export CF_TOKEN" before starting dehydrate?

For the first subdomain I used export CF_TOKEN="xxx" and ran "./dehydrate". The certificate has been downloaded successfully.

Then I added another subdomain to "domains.txt", and I started dehydrate again. 
There was an error "ERROR: Missing CF keys \ Terminated"

Can you please add to the README what needs to be set? For the ability to add additional domains and renew them.

Thanks
abe

**Comment by socram8888** [comment]
Hello Abe. That token indeed needs to be passed every time you run the script. I think you should be able to put `CF_TOKEN=xxx` in your config file, though.
