### ISSUE TITLE
Hook does not work with drill installed on Ubuntu 22.04

### ISSUE THREAD

**Issue by chennin** [socram8888/dehydrated-hook-cloudflare#8]
Hello, I updated dehydrated and dehydrated-hook-cloudflare today, and found that my renewal no longer worked.

The reason is that the hook passes `-Q` to `drill`, which, at least on Ubuntu 22.04 with drill 1.7.1, suppresses _all_ output.

https://github.com/socram8888/dehydrated-hook-cloudflare/blob/347780dd2bff5c4b24c50a8b76ee61bf73963b5e/cf-hook.sh#L25

```
# drill -Q google.com
#
```

This means that the `grep` that `resolve_record` uses can never succeed, because it will never find the string it wants. 

https://github.com/socram8888/dehydrated-hook-cloudflare/blob/347780dd2bff5c4b24c50a8b76ee61bf73963b5e/cf-hook.sh#L130

I briefly looked at the man page and did not see an equivalent to +short in this version. It seems that drill 1.8.0+ [changed the behavior of `-Q`](https://github.com/NLnetLabs/ldns/pull/138) to make output shorter.

I removed the `-Q` and my renewal worked again. Please consider that, or another workaround for everyone on Ubuntu 22.04 (still supported) or before, and Debian bullseye (currently oldstable) or before.

**Comment by socram8888** [comment]
I guess it could be possible to not pass the `-Q` at all and it should still work? Though I'm afraid whatever grep is trying to match might appear elsewhere in the output of drill.
